### ISSUE TITLE
Discussion: Medical Settings

### ISSUE THREAD

**Issue by KHunter-Arma** [ARandy-BADPMC/BADCO_Public_ACE_PatrolOpsV4_Insurgency#10]
I've been thinking about medical settings for some time. I disabled fractures, since they didn't exist when you guys last configured these settings as far as I know. They just jumped into the game "on their own" when introduced for the first time. It's happening way too much for a good Pub gameplay anyway. Almost every hit to the arm/leg results in a fracture. I thought disabling it altogether is best since all the other features and equipment are more than enough to keep the average first-time-ACE'r busy learning.  So that got me thinking... 

Isn't it too much that we have 4 different bandage types, for the kind of experience that we want to introduce? Most people have a really hard time understanding the medical system for the first time and I doubt most people know what the different bandages are really for. Quickclot is already useless since you guys have wounds reopening disabled (which is good I think). I think it would be best to disable "Advanced Bandages" which should replace all different bandaging options with a single "Bandage" option. We can then also remove all bandages in the Arsenal except for the basic field dressing. What do you think?

**Comment by ARandy-BADPMC** [comment]
Realistically its possible to play with one bandage type anyway and im sure thats what most pubs do and just spam elastic bandages. But i like having to think a bit about what im putting on (thats what she said), considering that its really not nessecary to pick which bandages. Id rathar leave it like this and if possible add wound reopening at a low chance so we get more of an emphasis on the medic slot and use of surgical kits. Basically right now everyone is just running a half medic loadout and getting away with spamming bandages and moving on. 

Are we still preparing players for pops with the pub server and do we want players who cant diferentiate 4 different bandages and their uses. Whats next allowing only M4s so people dont have to think what mags are compatible for what?

**Comment by KHunter-Arma** [comment]
We're past "preparing people for pops" now. This server has the potential to attract many random players (and it is already doing that) and right now there is hardly anyone to come online and teach people how to be a medic properly. Most people on there will never see the Realism server, realistically speaking *no pun intended*. All I'm seeing is clueless medics and people overdosing themselves with morphine. 

I actually went ahead and made the changes, just to see how people will react. If we get more experienced members to become more active on the server we can think about it upping the level again. We shouldn't lose perspective on how difficult all these features of ACE are to the average person that's realism-curious. Back in Arma 2, bandages, tourniquets and morphine-epi were the only things we had with ACE. We didn't even have saline/blood, if you remember. We still have that to deal with here at the very least. I'd rather have people know what they're doing to themselves rather than memorise a bandage effectiveness table and a sequence of operations meaningless to them.
